# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='image',
            field=models.ImageField(default=None, upload_to='images/commerces/'),
            preserve_default=False,
        ),
    ]
