# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'verbose_name': 'Barrio', 'verbose_name_plural': 'Barrios'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Sitio', 'verbose_name_plural': 'Sitios'},
        ),
        migrations.AlterModelOptions(
            name='sitecategory',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='siteimages',
            options={'verbose_name': 'Imagen Sitio', 'verbose_name_plural': 'Imagenes Sitio'},
        ),
    ]
